### ISSUE TITLE
How to access url helpers within generated doc?

### ISSUE THREAD

**Issue by Priya101** [trade-informatics/caracal-rails#2]
I have a link for show page within doc e.g users_url(@user). But this url is undefined within the doc.

**Comment by jdugan** [comment]
Because it would be unconventional to declare an `:id` parameter with an index route, I'm guessing the issue here is a simple typo.  

Did you perhaps intend to reference `user_url(@user)`?

**Comment by Priya101** [comment]
docx.p  @user.name, style: 'Title', align: :right
docx.p  "Created: #{@user.created_at}", style: 'Subtitle', align: :right
docx.p do
 link 'Show',  user_url(@user)
end

The first two line is working. But the link to show is throwing error:-
NoMethodError - undefined method `user_url' for #<Caracal::Core::Models::ParagraphModel:0x007ff832ab54f0>:

**Comment by Priya101** [comment]
Rails.application.routes.url_helpers.user_url(@user) is the fix for this issue.
