### ISSUE TITLE
How can i insert a page break after each li ?

### ISSUE THREAD

**Issue by Priya101** [trade-informatics/caracal-rails#3]
I have code like below:-
docx.ol do
 li 'first'
 li 'second'
end
I need to insert a page break after each li.
I used docx.page after li but that didn't worked.

**Comment by jdugan** [comment]
I don't believe list items (which are really just extensions of paragraphs) will take a page break right now.  I know they take a line break, but I don't think page breaks are supported.  Having written that, Word does support the feature you are requesting and it seems easy enough to implement.  I'll take a crack at it today.

Would you do me a favor?  This is a `caracal` concern, not a `caracal-rails` concern.  `caracal-rails` is only responsible for loading Caracal into the rails environment--it doesn't handle caracal syntax at all.  

Please open a new issue on the `caracal` project. I'm closing this issue as not relevant to this project.
