### ISSUE TITLE
Access Number Helpers in Caracal 

### ISSUE THREAD

**Issue by ohenrik** [trade-informatics/caracal-rails#4]
'I'm trying to access helpers inside the caracal template. However I'm getting an error telling me that the method does not exist. Is there any way i can access the number_to_currency helper in the `docx.caracal` template?

**Comment by ohenrik** [comment]
ah, nvm i ended up using `text ActiveSupport::NumberHelper.number_to_currency(project.revenue, precision: 0)` and got it working. However it might be convenient if helpers work directly. :)

**Comment by jdugan** [comment]
My guess is you're likely seeing the same thing mentioned in this Caracal issue. https://github.com/trade-informatics/caracal/issues/29

My response there clarifies what's happening inside Caracal and how to organize you're view accordingly.
