### ISSUE TITLE
Error in using caracal in rails 5

### ISSUE THREAD

**Issue by ariawanzero** [trade-informatics/caracal-rails#6]
I use it in my rails project but when i'm try this example i'm getting error this 
undefined method `keep_if' for "Droid Serif":String do you have any idea about this?

**Comment by jdugan** [comment]
The syntax on this project's README page is not intended to be a working example as much as an indication of how Caracal syntax works.  `caracal-rails` is really just a light-weight Rails shim for the `caracal` library.

Please try downloading and running the [example project](https://github.com/trade-informatics/caracal-example) referenced in the README and see if you get the same error.  That represents an out-of-box, canonical implementation of the libraries, and as such, it is the best introduction to what `caracal` can and cannot do.

I just updated the Gemfile of the example project to use the latest ruby and rails versions and it ran fine for me.  I think if you give that a try, it'll be of more assistance.
