### ISSUE TITLE
Interpolation for docx.p do block

### ISSUE THREAD

**Issue by dwood-somniainc** [trade-informatics/caracal-rails#9]
I am attempting to string together an object attribute and a sentence within the do block using text. For some odd reason, it says that the class is nil when I use instance variables inline

```
docx.p do
   text 'hello' @user.name  
end
```

How would you approach this issue?

**Comment by jdugan** [comment]
There's a section on lexical scoping near the bottom of the README.  I'd encourage you to read that and the comments on the closed issue it references.  That covers the topic, which is admittedly a little tricky in Caracal's case, pretty exhaustively.  

If you do that and you're still confused, ping me again out here, and I'll provide a direct answer to your exact question.

**Comment by jdugan** [comment]
Sorry. I meant near the bottom of the README for Caracal itself.  [Here](https://github.com/trade-informatics/caracal)

**Comment by dwood-somniainc** [comment]
Perfect! Thanks
